// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { config } from "./src/config/config"

export default defineConfig({
  schema: "src/database/prisma",
  migrations: {
    path: "src/database/migrations",
  },
  datasource: {
    url: config.DATABASE_URL,
  },
});
